spring.application.name=ticket
server.port=8080

spring.mongodb.uri=mongodb://root:root123@localhost:27017/ticketflow_db?authSource=admin

# JWT CONFIGURATION
app.jwt.secret=4a6a575462584a32386b4e6d42686b4d326173646667686a6b6c7a786376626e
app.jwt.expiration-ms=86400000

# CLOUDINARY CONFIGURATION
cloudinary.cloud-name=duddqeeeh
cloudinary.api-key=694258131245138
cloudinary.api-secret=eF8Zhsz05KkKiJvVXoBRZY1ijXI

# MAIL CONFIGURATION (Gmail Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ticketflowbooking@gmail.com
spring.mail.password=yfuepqofsnmcjstv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# FILE UPLOAD LIMITS
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
